package com.example.rimcat;

public class DataLogModel {
    // Page Trackers
    public static final int HOME_SCREEN = 0;
    public static final int INSTRUCTIONS_SCREEN_1 = 1;
    public static final int VIDEO_SCREEN = 2;
    public static final int KEYBOARD_SCREEN = 3;
    public static final int INSTRUCTIONS_SCREEN_2 = 4;
    public static final int EDUCATION_SCREEN = 5;
    public static final int TODAYS_DATE_SCREEN = 6;
    public static final int DAY_OF_WEEK_SCREEN = 7;
    public static final int SEASON_SCREEN = 8;
    public static final int INSTRUCTIONS_SCREEN_3 = 9;
    public static final int IMAGE_NAME_SCREEN = 10;
    public static final int INSTRUCTIONS_SCREEN_4 = 11;
    public static final int VERBAL_LEARNING_SCREEN_1 = 12;
    public static final int VERBAL_RECALL_SCREEN_1 = 13;
    public static final int INSTRUCTIONS_SCREEN_5 = 14;
    public static final int VERBAL_LEARNING_SCREEN_2 = 15;
    public static final int VERBAL_RECALL_SCREEN_2 = 16;
    public static final int INSTRUCTIONS_SCREEN_6 = 17;
    public static final int VERBAL_LEARNING_SCREEN_3 = 18;
    public static final int VERBAL_RECALL_SCREEN_3 = 19;
    public static final int INSTRUCTIONS_SCREEN_7 = 20;
    public static final int VERBAL_LEARNING_SCREEN_4 = 21;
    public static final int VERBAL_RECALL_SCREEN_4 = 22;
    public static final int INSTRUCTIONS_SCREEN_8 = 23;
    public static final int VERBAL_RECALL_SCREEN_5 = 24;
    public static final int INSTRUCTIONS_SCREEN_9 = 25;
    public static final int FIGURE_STUDY_SCREEN = 26;
    public static final int FIGURE_SELECT_SCREEN = 27;
    public static final int INSTRUCTIONS_SCREEN_10 = 28;
    public static final int DIGIT_SPAN_SCREEN = 29;
    public static final int INSTRUCTIONS_SCREEN_11 = 30;
    public static final int READ_COMP_STORY_SCREEN = 31;
    public static final int INSTRUCTIONS_SCREEN_12 = 32;
    public static final int COMPUTATION_SCREEN = 33;
    public static final int INSTRUCTIONS_SCREEN_13 = 34;
    public static final int VERBAL_RECALL_SCREEN_6 = 35;
    public static final int INSTRUCTIONS_SCREEN_14 = 36;
    public static final int VERBAL_RECOGNITION_SCREEN = 37;
    public static final int INSTRUCTIONS_SCREEN_15 = 38;
    public static final int SEMANTIC_CHOICE_SCREEN = 39;
    public static final int INSTRUCTIONS_SCREEN_16 = 40;
    public static final int FIGURE_SELECT_SCREEN_2 = 41;
    public static final int INSTRUCTIONS_SCREEN_17 = 42;
    public static final int READ_COMP_TEST_SCREEN = 43;
    public static final int INSTRUCTIONS_SCREEN_18 = 44;
    public static final int SEMANTIC_RELATEDNESS_SCREEN = 45;
    public static final int FINISH_SCREEN = 46;
}
